server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type_aliasese-package: com.example.entity

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: remote_user
    password: Wcfmaster2003$
    url: jdbc:mysql://162.14.71.188:3306/Datas?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
